config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get 'thanks', to: 'pages#thanks'
  get 'find_us', to: 'pages#find_us'
  get 'prices', to: 'pages#prices'
  resources :bookings, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  require 'net/http'
  require 'uri'

  after_create :send_booking_sms
  validates :phone, presence: true

  def send_booking_email
    UserMailer.booking(id).deliver_now
  end

  def send_booking_sms
    url_1 = "https://gate.smsaero.ru/send/?user=#{ENV['SMS_LOGIN']}&password=#{ENV['SMS_PASSWORD']}&to=#{ENV['SMS_NUMBER_1']}&text=Поступило бронирование в AWM. Номер #{phone}.&from=biznes"
    url_2 = "https://gate.smsaero.ru/send/?user=#{ENV['SMS_LOGIN']}&password=#{ENV['SMS_PASSWORD']}&to=#{ENV['SMS_NUMBER_2']}&text=Поступило бронирование в AWM. Номер #{phone}.&from=biznes"
    send_sms(url_1)
    send_sms(url_2)
  end

  def send_sms(url)
    uri = Addressable::URI.parse(url)
    Net::HTTP.get_response(uri)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    if @booking.save
      redirect_to thanks_path
    else
      render new_booking_path(@booking)
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:first_name, :last_name, :email, :phone, :model, :content)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def thanks
  end

  def find_us
  end

  def prices

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<% content_for(:title_tag) do %>
  Забронировать · Awm
<% end %>
<div class="container">
  <div class="row">
    <div class="col s12 m8 offset-m2">
      <h3 class="center-align booking-header"> Напите свой номер мы вам перезвоним </h3>
    <%= simple_form_for @booking do |f| %>
      <div class="row">
        <%= f.input :phone, label: 'Номер', error: 'Заполните поле', wrapper_html: { class: 'col s12' }, :input_html => { :type => "number" } %>
      </div>
      <%= f.submit 'ЗАБРОНИРОВАТЬ',  class: 'btn-bookings' %>
    <% end %>
    </div>
  </div>
</div>

<div class="line-footer">

</div>
<%= render "shared/footer"  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title_tag).blank? ? "Awm(Авм) —  Автосервис в Воронеже." : yield(:title_tag) %></title>
    <meta name="description" content="Профессиональный автосервис в Воронеже. Мы предоставляем огромный выбор услуг ремонта для любой машины и марки автомобиля" />
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta property="og:title" content="Awm — Автосервис с безупречной репутацией" />
    <meta property="og:type" content="article" />
    <meta property="og:url" content="https://www.awm-vrn.ru/" />
    <meta property="og:image" content="<%= image_url "fb.jpg" %>" />
    <meta property="og:description" content="Профессиональный автосервис в Воронеже. Мы предоставляем огромный выбор услуг ремонта для любой машины и марки автомобиля" />
    <meta property="og:site_name" content="Awm" />
    <meta name="google-site-verification" content="GEA6Wyb709CFogmE6ppjbeQKIhCsHhyI1IhOVAMov1o" />
    <meta name="yandex-verification" content="b95ddf4c711bb9e8" />
    <link rel="canonical" href="https://www.awm-vrn.ru/" />
    <link rel="alternate" hreflang="ru" href="https://www.awm-vrn.ru/" />
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= favicon_link_tag %>
    <script src="//api-maps.yandex.ru/2.1/?lang=ru_RU" type="text/javascript"></script>
  </head>
  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= yield(:after_js) %>
  </body>
</html>

app/views/pages/find_us.html.erb
<% content_for(:title_tag) do %>
  Найти нас · Awm
<% end %>
<div class="page-container">
  <div class="footer-cards">
    <div class="container">
      <div class="row">
        <div class="container">
          <h2 class="center-align title-find-us"> Найти нас </h2>
        </div>
        <div class="find-us-card">
          <div class="col s12 find-us-card-margin">
            <div class="row">
              <div class="col s6">
                <div class="footer-card left-align">
                  <h3 class="header-footer-card"> Мы открыты: </h3>
                </div>
              </div>
              <div class="col s6">
                <div class="center-align adding-margin">
                  <p class="header-text-findus"> Понедельник - Пятница </p>
                  <p class="header-time-findus"> 9:00 - 20:00 </p>
                  <p class="header-text-findus"> Суббота - Воскресенье </p>
                  <p class="header-time-findus find-us-end"> 9:00 - 20:00 </p>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="find-us-card">
          <div class="col s12 find-us-card-margin">
            <div class="row">
              <div class="col s6">
                <div class="footer-card left-align">
                  <h3 class="header-footer-card"> Адрес: </h3>
                </div>
              </div>
              <div class="col s6">
                <div class="center-align adding-margin">
                  <p class="header-address"> Проспект патриотов, 11a </p>
                  <p class="header-address"> г. Воронеж </p>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="find-us-card">
          <div class="col s12 find-us-card-margin">
            <div class="row">
              <div class="col s6">
                <div class="footer-card left-align">
                  <h3 class="header-footer-card">  Контакты: </h3>
                </div>
              </div>
              <div class="col s6">
                <div class="footer-card center-align">
                  <div class="phone-footer-find">
                    <div class="image-find">
                      <%= image_tag "phone.png" %>
                    </div>
                    <div class="phone-numbers">
                      <p>&nbsp;+7&nbsp; (473) &nbsp;202‑07-08</p>
                      <p>&nbsp;+7&nbsp; (473) &nbsp;202‑09-19</p>
                    </div>
                  </div>
                  <div class="phone-footer-find">
                    <div class="image-find">
                      <%= image_tag "email.png" %>
                    </div>
                    <div>
                      <p> contact@awm-vrn.ru </p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="hide-on-small-only hide-on-med-only" id="map"></div>
</div>
<% content_for(:after_js) do %>
  <script type="text/javascript">
    ymaps.ready(init);
      var myMap,
          myPlacemark;

      function init(){
          myMap = new ymaps.Map("map", {
              center: [51.642284, 39.139453],
              zoom: 16
          });

          myPlacemark = new ymaps.Placemark([51.64236238396459,39.13840434768797], {
              hintContent: '<%= image_tag 'awm.png', class: 'map-awm' %>', balloonContent: 'AWM автосервис'
          }, {
            preset: 'islands#redDotIconWithCaption'
          });

          myMap.geoObjects.add(myPlacemark);
      }
  </script>
<% end %>

app/views/pages/home.html.erb
<% content_for(:title_tag) do %>
  Awm(Авм) | Автосервис в Воронеже.
<% end %>

<div class="banner-home" style="background-image: linear-gradient(
      rgba(0, 0, 0, 0.3),
      rgba(0, 0, 0, 0.3)), url(<%= image_path 'banner-kappa.jpg' %>)">
  <div class="banner-content">
    <h1> Автосервис с безупречной репутацией.</h1>
    <%= link_to "Забронируй сейчас", new_booking_path, class: "btn-book" %>
  </div>
</div>
<div class="wrapper-cards">
  <div class="container cards">
    <h2 class="center-align"> Почему мы </h2>
    <div class="row">
      <div class="col s12 l4">
        <div class="autocard">
          <div class="header-card">
            <%= image_tag "card1.png" %>
            <h4> Опытные механики </h4>
          </div>
          <div class="content-card">
            <p>Чтобы гарантировать лучшее обслуживание нашим клиентам мы постоянно инвестируем в наших соотрудников</p>
          </div>
        </div>
      </div>
      <div class="col s12 l4">
        <div class="autocard">
          <div class="header-card">
            <%= image_tag "card2.png" %>
            <h4> Современные технологии </h4>
          </div>
          <div class="content-card">
            <p>Мы используем инновационное оборудование, чтобы обеспечить максимальную заботу о вашем автомобиле </p>
          </div>
        </div>
      </div>
      <div class="col s12 l4">
        <div class="autocard">
          <div class="header-card">
            <%= image_tag "card3.png" %>
            <h4>Корпоративные клиенты</h4>
          </div>
          <div class="content-card">
            <p> Мы работаем не только с физическими лицами, но и с корпоративными клиентами</p>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="container cards">
    <div class="row">
      <div class="col s12 l4">
        <div class="autocard">
          <div class="header-card">
            <%= image_tag "card4.png" %>
            <h4> Сложные операции </h4>
          </div>
          <div class="content-card">
            <p> Наша компания отремонтирует вашу машину даже после сильной аварии  </p>
          </div>
        </div>
      </div>
      <div class="col s12 l4">
        <div class="autocard">
          <div class="header-card">
            <%= image_tag "card5.png" %>
            <h4> Комфортные условия</h4>
          </div>
          <div class="content-card">
            <p> В нашем сервисе предоставленные все удобства, чтобы насладиться временем пока мы позаботимся о вашей машине </p>
          </div>
        </div>
      </div>
      <div class="col s12 l4">
        <div class="autocard">
          <div class="header-card">
            <%= image_tag "card6.png" %>
            <h4> Служебные записи </h4>
          </div>
          <div class="content-card">
            <p> Мы предоставляем услуги, которые были одобернны нашим клиентом и информируем его об стоймости услуги. Вы ведем подробные записи о проделанной работе  </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="hide-on-med-and-down ">
  <div class="what-we-serve">
    <h2 class="center-align serve"> Обслуживаем </h2>
    <div class="auto-carrosel">
        <div class="container flex-cars">
          <div class="swiper-container auto-carrosel-container">
            <div class="swiper-wrapper">
                <div class="swiper-slide car" style="background-image: url(<%= image_path "vw.png" %>)"></div>
                <div class="swiper-slide car" style="background-image: url(<%= image_path "toyota.png" %>)"></div>
                <div class="swiper-slide car" style="background-image: url(<%= image_path "audi.png" %>)"></div>
                <div class="swiper-slide car" style="background-image: url(<%= image_path "mercedes.png" %>)"></div>
                <div class="swiper-slide car" style="background-image: url(<%= image_path "chevrolet.png" %>)"></div>
                <div class="swiper-slide car" style="background-image: url(<%= image_path "honda.png" %>)"></div>
                <div class="swiper-slide car" style="background-image: url(<%= image_path "peugeot.png" %>)"></div>
                <div class="swiper-slide car" style="background-image: url(<%= image_path "mitsubishi.png" %>)"></div>
                <div class="swiper-slide car" style="background-image: url(<%= image_path "skoda.png" %>)"></div>
            </div>
            <!-- Add Arrows -->
          </div>
        </div>
          <div class="swiper-button-prev swiper-button-black arrow-left"></div>
          <div class="swiper-button-next swiper-button-black arrow-right"></div>
    </div>
  </div>
</div>

<div class="banner-service" style="background-image: linear-gradient(
      rgba(0, 0, 0, 0.5),
      rgba(0, 0, 0, 0.5)), url(<%= image_path 'kappa-service.jpg' %>);">
  <div class="content-banner-awm">
    <div class="row killing-margin-service-awm">
      <div class="col s12 l8">
        <h2 class="left-align service-header"> Наши услуги </h2>
        <div class="row">
          <div class="service-margin-row">
            <div class="service-margin-awm ">
              <div class="col s12 m4 l4">
                <div class="service-card-awm">
                  <%= image_tag 'service1.png' , class: 'service-card-img-awm'%>
                  <div class="service-card-content-awm">
                    <h4> Кондиционеры </h4>
                    <p> Замена, Заправка </p>
                  </div>
                </div>
              </div>
              <div class="col s12 m4 l4">
                <div class="service-card-awm">
                  <%= image_tag 'service2.png' , class: 'service-card-img-awm' %>
                  <div class="service-card-content-awm">
                    <h4> Компьютер </h4>
                    <p> Диагностика </p>
                  </div>
                </div>
              </div>
              <div class="col s12 m4 l4">
                <div class="service-card-awm">
                  <%= image_tag 'service3.png' , class: 'service-card-img-awm' %>
                  <div class="service-card-content-awm">
                    <h4> Шины </h4>
                    <p> Ремонт, Замена </p>
                  </div>
                </div>
              </div>
            </div>
            <div class="service-margin-awm ">
              <div class="col s12 m4 l4">
                <div class="service-card-awm">
                  <%= image_tag 'oil.png' , class: 'service-card-img-awm'%>
                  <div class="service-card-content-awm">
                    <h4> Масло </h4>
                    <p> Замена, Продажа </p>
                  </div>
                </div>
              </div>
              <div class="col s12 m4 l4">
                <div class="service-card-awm">
                  <%= image_tag 'elec.png' , class: 'service-card-img-awm' %>
                  <div class="service-card-content-awm">
                    <h4> Электроника </h4>
                    <p> Ремонт </p>
                  </div>
                </div>
              </div>
              <div class="col s12 m4 l4">
                <div class="service-card-awm">
                  <%= image_tag 'truba.png' , class: 'service-card-img-awm' %>
                  <div class="service-card-content-awm">
                    <h4> Выхлоп. Труба </h4>
                    <p> Ремонт, Замена </p>
                  </div>
                </div>
              </div>
            </div>
            <div class="service-margin-awm">
              <div class="col s12 m4 l4">
                <div class="service-card-awm">
                  <%= image_tag 'podveska.png' , class: 'service-card-img-awm'%>
                  <div class="service-card-content-awm">
                    <h4> Подвеска </h4>
                    <p> Ремнот, Замена </p>
                  </div>
                </div>
              </div>
              <div class="col s12 m4 l4">
                <div class="service-card-awm">
                  <%= image_tag 'remni.png' , class: 'service-card-img-awm' %>
                  <div class="service-card-content-awm">
                    <h4> Ремень ГРМ </h4>
                    <p> Ремонт, Замена </p>
                  </div>
                </div>
              </div>
              <div class="col s12 m4 l4">
                <div class="service-card-awm">
                  <%= image_tag 'details.png' , class: 'service-card-img-awm' %>
                  <div class="service-card-content-awm">
                    <h4> Запчасти </h4>
                    <p> Продажа </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>


      <div class="col s12 l4">
        <h2 class="left-align service-header"> Осмотр </h2>
        <div class="row">
          <div class="service-margin-row">
            <div class="service-margin-awm">
              <div class="col s12 m4 l12">
                <div class="service-card-awm">
                  <%= image_tag 'xod.png' , class: 'service-card-img-awm'%>
                  <div class="service-card-content-awm">
                    <h4 class="making-center-text"> Ходовая часть </h4>
                    <p class="hidep-banner"> Ремонт, Проверка </p>
                  </div>
                </div>
              </div>
              <div class="col s12 m4 l12">
                <div class="service-card-awm">
                  <%= image_tag 'podgotovka.png' , class: 'service-card-img-awm' %>
                  <div class="service-card-content-awm">
                    <h4 class="making-center-text"> Предпродажная подг. </h4>
                    <p class="hidep-banner"> Проверка </p>
                  </div>
                </div>
              </div>
              <div class="col s12 m4 l12">
                <div class="service-card-awm">
                  <%= image_tag 'osmotr.png' , class: 'service-card-img-awm' %>
                  <div class="service-card-content-awm">
                    <h4 class="making-center-text"> Выездной сервис </h4>
                    <p class="hide-banner"> Дополнительно </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container cards">
  <div class="row">
    <div class="col s12 l12">
      <div class="offers">
        <h2 class="center-align serve" style="margin-bottom: 15px;"> Акции </h2>
        <p style="font-size: 20px;" class="center-align"> Экономьте деньги с нашими текущими предложениями </p>

        <div class="offers-cards">
          <div class="offers-card">
            <div class="offers-card-price"> 0₽ </div>
            <p class="offers-card-info"> Шиномонтаж </p>
            <!-- <p style="margin-top: 0; font-size: 18px;"> Бесплатный шиномонтаж или сход-развал sза репост в вконтакте </p> -->
          </div>
          <div class="offers-card">
            <div class="offers-card-price"> 0₽ </div>
            <p class="offers-card-info"> Cход-развал </p>
            <!-- <p style="margin-top: 0; font-size: 18px;"> Бесплатный шиномонтаж или сход-развал sза репост в вконтакте </p> -->
          </div>
        </div>
        <p class="center-align" style="margin-top: 10px; font-size: 18px;"> Бесплатный шиномонтаж или сход-развал за репост в  <a target="_blank" href="https://vk.com/club178527091"> вконтакте </a> </p>

      </div>
    </div>
  </div>
</div>
<div class="line-footer" style="margin-top: 50px;">

</div>

<%= render 'shared/footer' %>


<% content_for(:after_js) do %>
  <script>
    var swiper = new Swiper('.swiper-container', {
      nextButton: '.swiper-button-next',
      prevButton: '.swiper-button-prev',
      loop: true,
      slidesPerView: 6,
      spaceBetween: 30,
    });
  </script>

<% end %>

app/views/pages/prices.html.erb
<% content_for(:title_tag) do %>
  Awm(Авм) | Цены.
<% end %>

<div class="container">
  <div class="row">
    <div class="col s12">
      <h4 style="text-align: center; margin-top: 40px;">  Цены на основные услуги AWM-сервис </h4>
      <table class="centered striped">
        <thead>
          <tr>
            <th>Услуга</th>
            <th> Стоимость, руб </th>
          </tr>
        </thead>

        <tbody>
          <tr>
            <td>Диагностика ходовой</td>
            <td>500</td>
          </tr>
          <tr>
            <td>Дезинфекция с учетом материалов</td>
            <td>1500</td>
          </tr>
          <tr>
            <td>Регулировка света фар</td>
            <td>400</td>
          </tr>
          <tr>
            <td>Замена масла в двигателе</td>
            <td>500</td>
          </tr>
          <tr>
            <td>Замена масла в КПП</td>
            <td>1000</td>
          </tr>
          <tr>
            <td>Замена масла в АКПП</td>
            <td>1500</td>
          </tr>
          <tr>
            <td>Замена воздушного фильтра</td>
            <td>200</td>
          </tr>
          <tr>
            <td>Замена топливного фильтра</td>
            <td>300</td>
          </tr>
          <tr>
            <td>Замена масла в мосту</td>
            <td>700</td>
          </tr>
          <tr>
            <td>Замена салонного фильтра</td>
            <td>300</td>
          </tr>
          <tr>
            <td>Заправка кондиционера</td>
            <td>1500</td>
          </tr>
          <tr>
            <td>Замена охлаждающей жидкости</td>
            <td>1000</td>
          </tr>
          <tr>
            <td>Замена тормозной жидкости</td>
            <td>1000</td>
          </tr>
          <tr>
            <td>Замена свечей зажигания</td>
            <td>400</td>
          </tr>
          <tr>
            <td>Замена тормозных колодок</td>
            <td>700</td>
          </tr>
          <tr>
            <td>Замена сцепления</td>
            <td>4000</td>
          </tr>
          <tr>
            <td>Замена ремня ГРМ</td>
            <td>2000</td>
          </tr>
          <tr>
            <td>Диагностика электронных систем</td>
            <td>500</td>
          </tr>
          <tr>
            <td>Развал-схождение</td>
            <td>1000</td>
          </tr>
        </tbody>
      </table>
      <br>
      *цены на некоторые позиции из прейскуранта могут отличаться в зависимости от индивидуальных особенностей, подробности уточняйте по нашему телефону 20-20-919
      <div class="car-container" style="margin-top: 70px;" >

        <%= image_tag 'car-prices.png', style: 'display: block; margin-left: auto; margin-right: auto;' %>
      </div>
    </div>
  </div>
</div>

<div class="line-footer">

</div>
<%= render 'shared/footer' %>

app/views/pages/thanks.html.erb
<% content_for(:title_tag) do %>
  Спасибо · Awm
<% end %>

<div class="banner-thanks" style="background-image: linear-gradient(
      rgba(0, 0, 0, 0.5),
      rgba(0, 0, 0, 0.5)), url(<%= image_path 'thanks-banner.jpg' %>)">
  <h1> Cпасибо </h1>
</div>

<div class="wrapper-thanks">
  <div class="row">
    <div class="col s12 m8 offset-m1 l8 offset-l1">
      <h2> Cпасибо за вашу заявку</h2>
      <p>Ваша заявка очень <strong>важна</strong> для нас. Наша команада свяжется с вами в ближайшее время</p>
      <p>Если у вас срочная проблема, вы всегда можете позвонить нам по телефону &ensp; +7 (473) 202-07-08 </p>

      <p id='thanks-start'>С уважение,</p>
      <p id='thanks-end'><strong>Команда AWM</strong></p>
    </div>
  </div>
</div>


<div class="line-footer">

</div>
<%= render 'shared/footer' %>

app/views/shared/_footer.html.erb
<div class="wrapper-footer">
  <div class="row">
    <div class="col s12 m6 l3">
      <div class="footer-block-awm">
        <div class="footer-block-awm-content">
          <h4 class="header-footer"> Адрес: </h4>
          <p class="header-address"> Проспект патриотов, 11a </p>
          <p class="header-address" id='city'> г. Воронеж </p>
          <a href="https://yandex.ru/maps/193/voronezh/?mode=search&ol=geo&ouri=ymapsbm1%3A%2F%2Fgeo%3Fll%3D39.139%252C51.642%26spn%3D0.001%252C0.001%26text%3D%25D0%25A0%25D0%25BE%25D1%2581%25D1%2581%25D0%25B8%25D1%258F%252C%2520%25D0%2592%25D0%25BE%25D1%2580%25D0%25BE%25D0%25BD%25D0%25B5%25D0%25B6%252C%2520%25D0%25BF%25D1%2580%25D0%25BE%25D1%2581%25D0%25BF%25D0%25B5%25D0%25BA%25D1%2582%2520%25D0%259F%25D0%25B0%25D1%2582%25D1%2580%25D0%25B8%25D0%25BE%25D1%2582%25D0%25BE%25D0%25B2%252C%25207%25D0%2590%2520&ll=39.139453%2C51.642284&z=16" class="btn-footer", target="_blank" > Найди нас на карте</a>
        </div>
      </div>
    </div>
    <div class="col s12 m6 l3">
      <div class="footer-block-awm">
        <div class="footer-block-awm-content">
          <h4 class="header-footer"> Контакты: </h4>
          <div class="phone-footer">
            <%= image_tag "phone.png" %>
            <div class="phone-numbers">
              <p>+7 (473) 202‑07-08</p>
              <p>+7 (473) 202‑09-19</p>
            </div>
          </div>
          <div class="phone-footer">
            <%= image_tag "email.png" %>
            <p> contact@awm-vrn.ru </p>
          </div>
        </div>
      </div>
    </div>
    <div class="col s12 m6 l3">
      <div class="footer-block-awm">
        <div class="footer-block-awm-content">
          <h4 class="header-footer"> Мы открыты: </h4>
          <p class="header-text"> Понедельник - Пятница </p>
          <p class="header-time"> 9:00 - 20:00 </p>
          <p class="header-text"> Суббота - Воскресенье </p>
          <p class="header-time"> 9:00 - 20:00 </p>
        </div>
      </div>
    </div>
    <div class="col s12 m6 l3">
      <div class="footer-block-awm">
        <div class="footer-block-awm-content">
          <h4 class="header-footer"> Наши соцсети: </h4>
          <a class="footer-social-links footer-social-links-vk" href="https://vk.com/club178527091" target="_blank"> <i class="fa fa-vk"></i> </a>
          <a class=" footer-social-links footer-social-links-insta" href="https://www.instagram.com/avtoservis_vrn/" target="_blank"> <i class="fa fa-instagram"></i> </a>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-awm">
  <!-- Logo -->
  <%= link_to root_path, class: 'navbar-awm-brand' do %>
    <%= image_tag "awm123.jpg" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-awm-right hide-on-small-only hide-on-med-only">
    <div class="navbar-awm-item">
      <%= link_to "Главная", root_path, class: "navbar-awm-link" %>
    </div>
    <div class="navbar-awm-item">
      <%= link_to 'Цены', prices_path, class: "navbar-awm-link" %>
    </div>
     <div class="navbar-awm-item">
      <%= link_to "Найти нас", find_us_url, class: "navbar-awm-link" %>
    </div>

    <div class="navbar-awm-item">
      <%= link_to "Забронировать", new_booking_path, class: "navbar-awm-link navbar-cta" %>
    </div>
  </div>
<!-- navbar-awm-dropdown-menu -->

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-awm-item hide-on-large-only ">
    <a href="#" class="button-collapse" data-activates="mobile-demo" id="navbar-awm-menu">  <i class="fa fa-bars" ></i>  </a>
    <ul id='mobile-demo' class="side-nav side-menu-awm">
      <li>
        <%= link_to root_path do  %>
          <i class="fa fa-home icon-navbar-awm" aria-hidden="true"></i>
          <p> Главная </p>
        <% end %>
      </li>
      <li>
        <%= link_to new_booking_path do  %>
          <i class="fa fa-wrench icon-navbar-awm" aria-hidden="true"> </i>
          <p> Забронировать </p>
        <% end %>
      </li>
      <li>
        <%= link_to find_us_url do  %>
          <i class="fa fa-search icon-navbar-awm" aria-hidden="true"></i>
          <p> Найти нас </p>
        <% end %>
      </li>
    </ul>
  </div>
</div>